#Self Contained language file
####################################### 
#English
####################################### 
#User Model
msgcat::mcset en  "This username doesn't exist" "This username doesn't exist"
msgcat::mcset en "The password you entered is incorrect" "The password you entered is incorrect" 
msgcat::mcset en "Nice going sherlock, you've just temporarily blocked
					your account for 3 hours because you entered too many wrong passwords.." \
					"Nice going sherlock, you've just temporarily blocked
					your account for 3 hours because you entered too many wrong passwords.." 
msgcat::mcset en  "You can't login because you're banned! If you think this is a mistake, contact us." "You can't login because you're banned! If you think this is a mistake, contact us."
msgcat::mcset en  "This account is still temporarily blocked untill %s
				because someone tried too many wrong passwords.."   "This account is still temporarily blocked untill %s
				because someone tried too many wrong passwords.."  


#User Controller

msgcat::mcset en "Account created successfully" "Account created successfully" 
msgcat::mcset en "You've successfully registered. 
				You will recieve an e-mail with an activation link.
				Please click on it to activate your account and start saving time." "You've successfully registered. 
				You will recieve an e-mail with an activation link.
				Please click on it to activate your account and start saving time." 
msgcat::mcset en "Your new account at %s" "Your new account at %s" 
msgcat::mcset en "Activation code incorrect." "Activation code incorrect." 
msgcat::mcset en "No such activation code seems to exist" "No such activation code seems to exist" 
msgcat::mcset en "Account is already activated." "Account is already activated."
msgcat::mcset en "This account is already activated, you don't need to activate it again.." 
msgcat::mcset en "You've successfully activated your account. You may now login!" "You've successfully activated your account. You may now login!" 
msgcat::mcset en "No such username or e-mail can be found!" "No such username or e-mail can be found!" 
msgcat::mcset en "A password reset has already been requested some time ago.
				You need to wait 3 hours between consequent password resets. Did you verify your e-mail? " "A password reset has already been requested some time ago.
				You need to wait 3 hours between consequent password resets. Did you verify your e-mail? "
msgcat::mcset en "You will recieve an e-mail with an password reset link.
				Please click on it to change your account's password." "You will recieve an e-mail with an password reset link.
				Please click on it to change your account's password." 
msgcat::mcset en "Resetting your password at %s" 
msgcat::mcset en "You've changed your password, you may now login!" 
msgcat::mcset en "Your password has been successfully changed." 
msgcat::mcset en "This code doesn't exist" "This code doesn't exist" 
msgcat::mcset en  "Sorry this reset password code doesn't exist.." "Sorry this reset password code doesn't exist.."
msgcat::mcset en "Tried to search for id %d but just couldn't find it!" "Tried to search for id %d but just couldn't find it!"   
msgcat::mcset en "Not validating, sorry! %s" 

msgcat::mcmset en {
	t:404notfound "404 Not found, sorry :)"
	p:404notfound "Couldn't find the thing you were searching for. %s"
	"Something went a little wrong.." "Something went a little wrong.."
 	"Error: %s Details: %s on line %d" "Error: %s Details: %s on line %d"
	t:unauthorized "You aren't authorized.." 
	p:unauthorized 	"Sorry, you can't view this page. 
	Either you are no authorized to access it or the user access rights for this page are too strict."

}
#Validation and Database File
msgcat::mcmset en {
	a b	
}


#Database file

msgcat::mcmset en {
	c d
}



